use_frameworks!

platform :ios, '12.0'

target 'ModuleResourceLoader_Example' do
  pod 'ModuleResourceLoader', :path => '../'

  target 'ModuleResourceLoader_Tests' do
    inherit! :search_paths

    
  end
end
